name: CI

on:
  push:
    branches: [ "homework4" ]
  pull_request:
    branches: [ "homework4" ]
  workflow_dispatch:

jobs:
  makeBin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: create a bin directory
        run: make

      - name: Set executable a tests
        run: chmod +x ./tests/test*.sh

      - name: Test exercise 1
        run: make test1

      - name: Test exercise 2
        run: make test2

      - name: Test exercise 3
        run: make test3

      - name: Test exercise 4
        run: make test4

      - name: Test exercise 5
        run: make test5

      - name: Clean
        run: make clean

  test1:
    needs: makeBin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: running tests for join_int_arrays
        run: make test1

  test2:
    needs: makeBin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: running tests for join_and_sort_int_arrays
        run: make test2

  test3:
    needs: makeBin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: running tests for get_min_and_max_from_int_array
        run: make test3
